### ISSUE TITLE
Unable to view ace files from ae

### ISSUE THREAD

**Issue by drserajames** [acorg/Racmacs#173]
When I read an ace file generated with Eu's system, I used to be able to view the maps. Not I get the following error:

```
> packageVersion("Racmacs")
[1] ‘1.2.7’

> view(map)
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 1, 0
```

View works fine for maps made in Racmacs.

I will slack you the map, Sam.

I don't know if it's relevant, but I recently updated my Mac to Sonoma and didn't have issues prior to that.

**Comment by shwilks** [comment]
ah, yes, this is not a Racmacs problem per-se but a namespace issue.  They added a new function `view()` instead of `View()` to the `tibble` tidyverse package, so if you load tibble after Racmacs the Racmacs view gets clobbered in your global namespace (there is a warning when this happens, which of course every user dutifully pays lots of attention to).

I could add an additional alias function with a more distinct name given that tibble is such a common package.  To avoid the namespace clash you can simply be specific and call `Racmacs::view(map)`.
