### ISSUE TITLE
Error while installing/loading Racmacs in R v4.0.5

### ISSUE THREAD

**Issue by dven42** [acorg/Racmacs#56]
Racmacs worked fine for me on R v3.6. I updated it to R v4.0.5 now and am getting an error message while installing the latest version using `devtools::install_github("acorg/Racmacs")`

Attaching the complete output but the problem seems to be this error: 

> ERROR: dependency ‘rmarchingcubes’ is not available for package ‘Racmacs’

I tried installing an older version of Racmacs after removing.packages. Got no errors during installation but when I tried to load the library I got the following error: 

> Error: package or namespace load failed for ‘Racmacs’:
>  package ‘Racmacs’ was installed before R 4.0.0: please re-install it

None of the suggestions I found on StackExchange for similar errors solved this problem. 

Any help appreciated, thanks! 

----Session info-----

> R version 4.0.5 (2021-03-31)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Big Sur 10.16
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] rstudioapi_0.13   knitr_1.33        magrittr_2.0.1    usethis_2.0.1     devtools_2.4.1    pkgload_1.2.1    
>  [7] R6_2.5.0          rlang_0.4.11      fastmap_1.1.0     tools_4.0.5       pkgbuild_1.2.0    xfun_0.22        
> [13] sessioninfo_1.1.1 tinytex_0.31      cli_2.5.0         withr_2.4.2       htmltools_0.5.1.1 ellipsis_0.3.2   
> [19] remotes_2.3.0     yaml_2.2.1        digest_0.6.27     rprojroot_2.0.2   lifecycle_1.0.0   crayon_1.4.1     
> [25] processx_3.5.2    purrr_0.3.4       callr_3.7.0       fs_1.5.0          ps_1.6.0          curl_4.3.1       
> [31] testthat_3.0.2    glue_1.4.2        memoise_2.0.0     cachem_1.0.4      evaluate_0.14     rmarkdown_2.8    
> [37] compiler_4.0.5    desc_1.3.0        prettyunits_1.1.1
> 

[errormessage_Racmacs.txt](https://github.com/acorg/Racmacs/files/6469271/errormessage_Racmacs.txt)

**Comment by shwilks** [comment]
Thanks for the error report, as you've worked out  it looks like as part of the installation process it is trying and failing to install the dependency package `rmarchingcubes`.  This in turn looks like it is because the default mac os compiler (clang++) can't find the fortran library it needs to link to - this is a well reported problem unfortunately.  The solution should be to follow the instructions on changing your default compiler to be g++, https://acorg.github.io/Racmacs/#building-racmacs-to-run-code-in-parallel

I should probably add a comment in the installation instructions about the sort of error you are having since it's a common issue on macs with a standard compiler setup up I think.  I should also add some pre-built binary versions of the package, at least for mac versions, to save people having to deal with all the compilation issues, this is a good reminder to do that.  In the meantime I hope switching to the g++ compiler solves the problem for you but let me know if you have any issues.

Sam

**Comment by dven42** [comment]
Thanks Sam. Forgot to mention that I updated my mac to Big Sur so yes I have gcc but the defaults may have been altered. I reinstalled gcc, made the Makevars file in .R and added those lines, but I had to change the versions to 11 instead of 10.
