### ISSUE TITLE
hemisphering in GUI - bug?

### ISSUE THREAD

**Issue by CarlijnB** [acorg/Racmacs#65]
Hi Sam,

I've just loaded the GUI on Racmacs v.1.1.9 , with a 2D map.
When clicking on hemisphering, the shiny app crashes and raises the following error:

Warning: Error in ptHemisphering: could not find function "ptHemisphering"
  2: shiny::runApp
  1: runGUI

(When checking for hemipshering directly in R rather than the UI, I don't get any error but I don't get any obvious results either)

**Comment by shwilks** [comment]
Thanks for reporting all this stuff, I can't reproduce the hemisphering error in the GUI I think this is something I fixed after version 1.1.9 though since I remember some errors like that, so I would suggest giving it a go with the latest version.  When you check for it directly, I realise it's a bit dumb since it doesn't print any output but you will see any hemisphering points indicated if you do e.g. `view(checkHemisphering(map))`.  I should clearly update this so that you get some output telling you whether any hemisphering points were found or not

**Comment by shwilks** [comment]
ah, and sorry, when I say latest version I actually meant the latest version on my fork at `shwilks/Racmacs` which is at 1.1.12

**Comment by CarlijnB** [comment]
Thank you Sam for the suggestion, I'll give 1.1.12 a try and report back.
